<a href="https://colab.research.google.com/github/CharlesPrado23/Bootcamp_TurmaNoite/blob/main/Conteudo_02/Exerc%C3%ADcios_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
### Questão 1
### Use o método np.unique para retornar um array sem duplicatas

In [3]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
### Questão 2
### crie uma matriz (4,3) usando o método np.random.randn(x,y)

In [7]:
arr_ = np.array(np.random.randn(4,3))
arr_

array([[-1.05007352, -1.39958575, -0.25340962],
       [-0.50428281, -0.06770335, -1.64137883],
       [ 0.38555046, -0.25715753, -0.64406452],
       [-0.65549412,  0.95352717, -0.14171855]])

In [ ]:
### Questão 3 
### Retorne os elementos entre as linhas 2 e 3 ; e entre as colunas 1 e 2 
### Use o conceito de slice e armazene o resultada em outro array

In [17]:
arr_slice = arr_[1:3,:2]

array([[-0.50428281, -0.06770335],
       [ 0.38555046, -0.25715753]])

In [ ]:
### Questão 4 
### Calcule o valor médio da matriz da Questão 2 
### Calcule o valor médio da matriz da Questão 2 na direção horizontal
### Calcule o valor médio da matriz da Questão 2 na direção vertical

In [18]:
arr_.mean()

-0.4396492460588537

In [20]:
arr_.mean(axis=1)

array([-0.90102296, -0.73778833, -0.17189053,  0.05210483])

In [21]:
arr_.mean(axis=0)

array([-0.456075  , -0.19272986, -0.67014288])

In [ ]:
### Questão 5
### usando o método arange , crie um array com 50 posições 
### Modifique todos os valores para o valor igual a 1 
### Usando o método reshape crie uma matriz (10,50)

In [33]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
arr_q5 += 1

In [31]:
arr_q5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [32]:
arr_q5 = arr_q5/arr_q5
arr_q5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
arr_q5[arr_q5 >= 0] = 1

In [38]:
arr_q5

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [39]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
arr_q5[0:] = 1

In [41]:
arr_q5

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [52]:
np.full(50,5, dtype=str)

array(['5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
       '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
       '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
       '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5'], dtype='<U1')

In [ ]:
### Usando o método reshape crie uma matriz (10,50)

In [58]:
arr_q5 = np.arange(50)
arr_q5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
arr_q5.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])