In [2]:
import pandas as pd
import numpy as np

In [3]:
f = "Abc'"

In [4]:
if f.isalpha():
    print('oi')
else:
    print("não deu certo")

não deu certo


In [5]:
a = '22233344455'

In [6]:
print(f"{a[0:3]}.{a[3:6]}.{a[6:9]}-{a[9:]}")

222.333.444-55


In [7]:
x = input('Insira um número: ')
if x.isnumeric() == True and (int(x)<0 or x.isalpha):
    print('Válido. É possível.')
else:
    print('Não transformou.')

Não transformou.


In [8]:
z = input('Insira um valor')
if z.isnumeric() == True or (z[0]=='-' and z[1:].isnumeric()==True):
    print('É um número.')
else:
    print('É uma string.')

É um número.


In [9]:
y = input()
if y.isalnum() == True:
    print('Funciona')
else:
    print('Não funciona')

Não funciona


In [11]:
atletas = {'fernando': 3,'bernardo': 6, 'adriana':2}
atletas_organizado = dict(sorted(atletas.items(), key = lambda x: x[1], reverse=True))
count= 1
for i in atletas_organizado:
  print(f'{count}º lugar - {i} - {atletas_organizado[i]:.2f}')
  count+=1

1º lugar - bernardo - 6.00
2º lugar - fernando - 3.00
3º lugar - adriana - 2.00


In [12]:
x = 'bernardo.10'

In [13]:
x = list(x)
print(x)
while (''.join(x)).isalpha() == False:
    for i in x:
        if i.isalpha()==False:
            x.remove(i)
print(x)


['b', 'e', 'r', 'n', 'a', 'r', 'd', 'o', '.', '1', '0']
['b', 'e', 'r', 'n', 'a', 'r', 'd', 'o']


In [14]:
string = '"Abcd"'
print(string)

"Abcd"


In [15]:
string = 'Abcd\n'
print(string)
string = list(string)
print(string)
for i in string:
    if i.isalpha() == False:
        string.pop(string.index(i))
print("".join(string))

Abcd

['A', 'b', 'c', 'd', '\n']
Abcd


In [16]:
string = 'Abcd\n'
print(string)
print(list(string))
if '\n' in string:
    my_list = string.split('\n')
    my_list.pop(my_list.index(""))
    
print("".join(my_list))
print(list("".join(my_list)))

    

Abcd

['A', 'b', 'c', 'd', '\n']
Abcd
['A', 'b', 'c', 'd']


In [17]:
i = '2.5'

In [18]:
if ("." in list(i)) and (("".join(i.split("."))).isnumeric() == True):
    print("Deu certo")

Deu certo


In [19]:
arr_ex = np.array(range(1,11))

In [20]:
arr_ex

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_ex *= 5

In [22]:
arr_ex

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
data = np.random.randint(-10,10, (2,3))
print(data)
print(type(data))

[[ -2 -10  -1]
 [  7   0   9]]
<class 'numpy.ndarray'>


In [24]:
pd.DataFrame(data)

,0,1,2
0,-2,-10,-1
1,7,0,9


In [25]:
for i in range(len(data)):
    print(data[i,1])

-10
0


In [26]:
len(data[0])

3

In [27]:
import pandas as pd
import numpy as np

In [28]:
starbucks_csv = pd.read_csv('starbucks.csv')

In [29]:
starbucks_csv

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,350,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,350,9.0,64,7,6,bakery
2,3,Apple Fritter,420,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,420,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,390,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,300,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,300,4.0,57,3,10,parfait


In [30]:
starbucks_csv.dtypes

ID            int64
item         object
calories      int64
fat         float64
carb          int64
fiber         int64
protein       int64
type         object
dtype: object

In [31]:
starbucks = starbucks_csv.copy()

In [32]:
starbucks

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,350,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,350,9.0,64,7,6,bakery
2,3,Apple Fritter,420,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,420,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,390,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,300,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,300,4.0,57,3,10,parfait


In [33]:
# starbucks['ID'] = starbucks['ID'].astype('object')
starbucks['ID'] = starbucks['ID'].apply(str)

In [34]:
starbucks['ID']

0      1
1      2
2      3
3      4
4      5
      ..
72    73
73    74
74    75
75    76
76    77
Name: ID, Length: 77, dtype: object

In [35]:
starbucks.dtypes

ID           object
item         object
calories      int64
fat         float64
carb          int64
fiber         int64
protein       int64
type         object
dtype: object

In [36]:
starbucks

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,350,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,350,9.0,64,7,6,bakery
2,3,Apple Fritter,420,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,420,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,390,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,300,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,300,4.0,57,3,10,parfait


In [37]:
print(type(starbucks['ID'][0]))
starbucks['ID'][0] + starbucks['ID'][1]
# Pq mudando o dtype da coluna não consigo alterar os tipo dos seus valores

<class 'str'>


'12'

In [38]:
starbucks.sort_values('calories',ascending=False)

,ID,item,calories,fat,carb,fiber,protein,type
61,62,Sausage & Cheddar Classic Breakfast Sandwich,500,28.0,41,0,19,hot breakfast
21,22,Iced Lemon Pound Cake,490,23.0,67,0,5,bakery
3,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
40,41,Zucchini Walnut Muffin,490,28.0,52,2,7,bakery
16,17,Cranberry Orange Scone,490,18.0,73,2,8,bakery
...,...,...,...,...,...,...,...,...
63,64,Starbucks Perfect Oatmeal,140,2.5,25,4,5,hot breakfast
30,31,Petite Vanilla Bean Scone,140,5.0,21,0,0,bakery
18,19,Double Fudge Mini Doughnut,130,7.0,16,0,0,bakery
4,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery


In [39]:
more_calories = (starbucks.sort_values('calories',ascending=False)).reset_index(drop=True)

In [40]:
more_calories

,ID,item,calories,fat,carb,fiber,protein,type
0,62,Sausage & Cheddar Classic Breakfast Sandwich,500,28.0,41,0,19,hot breakfast
1,22,Iced Lemon Pound Cake,490,23.0,67,0,5,bakery
2,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
3,41,Zucchini Walnut Muffin,490,28.0,52,2,7,bakery
4,17,Cranberry Orange Scone,490,18.0,73,2,8,bakery
...,...,...,...,...,...,...,...,...
72,64,Starbucks Perfect Oatmeal,140,2.5,25,4,5,hot breakfast
73,31,Petite Vanilla Bean Scone,140,5.0,21,0,0,bakery
74,19,Double Fudge Mini Doughnut,130,7.0,16,0,0,bakery
75,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery


In [41]:
more_calories

,ID,item,calories,fat,carb,fiber,protein,type
0,62,Sausage & Cheddar Classic Breakfast Sandwich,500,28.0,41,0,19,hot breakfast
1,22,Iced Lemon Pound Cake,490,23.0,67,0,5,bakery
2,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
3,41,Zucchini Walnut Muffin,490,28.0,52,2,7,bakery
4,17,Cranberry Orange Scone,490,18.0,73,2,8,bakery
...,...,...,...,...,...,...,...,...
72,64,Starbucks Perfect Oatmeal,140,2.5,25,4,5,hot breakfast
73,31,Petite Vanilla Bean Scone,140,5.0,21,0,0,bakery
74,19,Double Fudge Mini Doughnut,130,7.0,16,0,0,bakery
75,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery


In [42]:
less_fat = (starbucks.sort_values('fat')).reset_index(drop=True)

In [43]:
less_fat

,ID,item,calories,fat,carb,fiber,protein,type
0,67,Deluxe Fruit Blend,80,0.0,20,2,0,salad
1,32,Plain Bagel,280,1.0,59,2,9,bakery
2,20,Everything with Cheese Bagel,280,2.0,56,2,10,bakery
3,64,Starbucks Perfect Oatmeal,140,2.5,25,4,5,hot breakfast
4,28,Multigrain Bagel,300,3.0,60,6,15,bakery
...,...,...,...,...,...,...,...,...
72,47,Salumi & Cheese,420,26.0,22,3,25,bistro box
73,69,Egg Salad Sandwich,460,27.0,37,5,22,sandwich
74,42,Cheese & Fruit,480,28.0,39,6,18,bistro box
75,41,Zucchini Walnut Muffin,490,28.0,52,2,7,bakery


In [42]:
set(less_fat['type'].values)

{'bakery',
 'bistro box',
 'hot breakfast',
 'parfait',
 'petite',
 'salad',
 'sandwich'}

In [43]:
less_fat[less_fat['type'] == 'bakery']

,ID,item,calories,fat,carb,fiber,protein,type
1,32,Plain Bagel,280,1.0,59,2,9,bakery
2,20,Everything with Cheese Bagel,280,2.0,56,2,10,bakery
4,28,Multigrain Bagel,300,3.0,60,6,15,bakery
6,26,Marshmallow Dream Bar,210,4.0,43,0,0,bakery
8,15,Chonga Bagel,310,5.0,52,3,12,bakery
9,31,Petite Vanilla Bean Scone,140,5.0,21,0,0,bakery
10,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery
11,19,Double Fudge Mini Doughnut,130,7.0,16,0,0,bakery
16,37,Reduced-Fat Banana Chocolate Chip Coffee Cake,400,8.0,80,4,5,bakery
18,1,8-Grain Roll,350,8.0,67,5,10,bakery


In [44]:
len(less_fat[less_fat['type'] == 'bakery'])

41

In [45]:
for i in set(less_fat['type'].values):
    print(i, len(less_fat[less_fat['type'] == i]))

hot breakfast 8
bistro box 8
salad 1
parfait 3
petite 9
sandwich 7
bakery 41


In [46]:
print(f'''
{starbucks['calories'].mean()}
{starbucks['fat'].mean()}
{starbucks['carb'].mean()}
{starbucks['fiber'].mean()}
{starbucks['protein'].mean()}
''')


338.83116883116884
13.766233766233766
44.87012987012987
2.220779220779221
9.480519480519481



In [47]:
starbucks.mean(numeric_only=True)

calories    338.831169
fat          13.766234
carb         44.870130
fiber         2.220779
protein       9.480519
dtype: float64

In [48]:
starbucks.std(numeric_only=True)

calories    105.368701
fat           7.095488
carb         16.551634
fiber         2.112764
protein       8.079556
dtype: float64

In [49]:
std_starbucks1 = starbucks.copy()

In [50]:
std_starbucks1

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,350,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,350,9.0,64,7,6,bakery
2,3,Apple Fritter,420,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,420,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,390,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,300,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,300,4.0,57,3,10,parfait


In [51]:
std_starbucks1['calories'].std()

105.36870135978438

In [52]:
std_starbucks1['calories'] = std_starbucks1['calories']/std_starbucks1['calories'].max()

In [53]:
std_starbucks1

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,0.70,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,0.70,9.0,64,7,6,bakery
2,3,Apple Fritter,0.84,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,0.98,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,0.26,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,0.84,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,0.78,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,0.60,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,0.60,4.0,57,3,10,parfait


In [61]:
std_starbucks1.sort_values('calories').reset_index()[:5]

,index,ID,item,calories,fat,carb,fiber,protein,type
0,66,67,Deluxe Fruit Blend,0.16,0.0,20,2,0,salad
1,4,5,Birthday Cake Mini Doughnut,0.26,6.0,17,0,0,bakery
2,18,19,Double Fudge Mini Doughnut,0.26,7.0,16,0,0,bakery
3,30,31,Petite Vanilla Bean Scone,0.28,5.0,21,0,0,bakery
4,63,64,Starbucks Perfect Oatmeal,0.28,2.5,25,4,5,hot breakfast


In [62]:
std_starbucks2 = starbucks.copy()
std_starbucks2

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,350,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,350,9.0,64,7,6,bakery
2,3,Apple Fritter,420,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,490,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,130,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,420,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,390,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,300,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,300,4.0,57,3,10,parfait


In [66]:
std_starbucks2['calories'] = (std_starbucks2['calories'] - std_starbucks2['calories'].mean())/(std_starbucks2['calories'].std())

In [72]:
std_starbucks2

,ID,item,calories,fat,carb,fiber,protein,type
0,1,8-Grain Roll,0.105998,8.0,67,5,10,bakery
1,2,Apple Bran Muffin,0.105998,9.0,64,7,6,bakery
2,3,Apple Fritter,0.770332,20.0,59,0,5,bakery
3,4,Banana Nut Loaf,1.434665,19.0,75,4,7,bakery
4,5,Birthday Cake Mini Doughnut,-1.981909,6.0,17,0,0,bakery
...,...,...,...,...,...,...,...,...
72,73,Tarragon Chicken Salad Sandwich,0.770332,13.0,46,6,32,sandwich
73,74,Turkey & Swiss Sandwich,0.485617,13.0,36,2,34,sandwich
74,75,Greek Yogurt Honey Parfait,-0.368527,12.0,44,0,8,parfait
75,76,Peach Raspberry Yogurt Parfait,-0.368527,4.0,57,3,10,parfait


In [68]:
std_starbucks2['calories'].mean()

2.739511359464672e-17

In [44]:
import numpy as np

In [45]:
arr_ = np.arange(1000)

In [47]:
arr_.mean()

499.5

In [53]:
arr_ex = arr_ - arr_.mean()
arr_ex.mean()

0.0

In [57]:
arr2 = np.array([3,4,5])

In [49]:
arr2

array([3, 4, 5])

In [50]:
arr2.mean()

4.0

In [51]:
arr3 = arr2 - arr2.mean()
arr3

array([-1.,  0.,  1.])

In [52]:
arr3.mean()

0.0

In [54]:
arr3.std()

0.816496580927726

In [55]:
arr2

array([3, 4, 5])

In [60]:
arr_05 = arr2/arr2.std()

In [61]:
arr_05.std()

0.9999999999999999

In [70]:
arr_ = np.arange(1000)

In [71]:
arr_total = (arr_ - arr_.mean())/ arr_.std()

In [72]:
arr_total.mean()

0.0

In [73]:
arr_total.std()

0.9999999999999999